t=(1,2,3)
print(t)
y=(1,2,3,4,['chintu','ex'])
print(y)
print(type(y))
print(y[4][1])
print(y[1:2])
print(y[:])
y[4][1]='mintu'
print(y)
#del t
print(2 in t)
sorted_tupple=sorted(t)
print(sorted_tupple)
print(t)